# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-30 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coligacao',
            name='candidatos',
        ),
        migrations.AddField(
            model_name='coligacao',
            name='candidatos',
            field=models.ManyToManyField(to='candidatos.Candidato'),
        ),
    ]
