from .Candidato import Candidato
from .Candidatura import Candidatura
from .Cargo import Cargo
from .Coligacao import Coligacao
from .Coligacao_Partidos import Coligacao_Partidos
from .Eleicao import Eleicao
from .Local_Eleicao import Local_Eleicao
from .Estado_Nascimento import Estado_Nascimento
from .Municipio import Municipio
from .Partido import Partido
from .Turno_Eleicao import Turno_Eleicao
