from .Candidato import Candidato
from .Candidatura import Candidatura
from .Cargo import Cargo
from .Coligacao import Coligacao
from .Eleicao import Eleicao
from .Local_Nascimento import Local_Nascimento
from .Localidade import Localidade
from .Municipio import Municipio
from .Partido import Partido
